# Configuración de Enemigos

ENEMIES = {
    ###ENEMIGOS COMUNES
    "Rata Mutante": {
        "emoji": "⚠️",
        "hp": 30,
        "daño": (3, 8),
        "peso": 60,
        "lugares": [
            "Metro",
            "Hospital",
            "Escuela",
        ],
        "loot_overos": (1, 6),
        "loot_item": None,
        "items": [{"item": "Chatarra", "chance": 60, "cantidad": (1, 2)}],
        "efecto_probabilidad": 0,
        "color": 0xFFD000,
    },
    "Saqueador": {
        "emoji": "⚠️",
        "hp": 65,
        "daño": (8, 15),
        "peso": 40,
        "lugares": ["Gasolinera", "Comisaría", "Supermercado"],
        "loot_overos": (20, 40),
        "loot_item": None,
        "items": [
            {"item": "Venda", "chance": 50, "cantidad": (1, 2)},
            {"item": "Alcohol medicinal", "chance": 30, "cantidad": (1, 1)},
            {"item": "Comida enlatada", "chance": 40, "cantidad": (1, 1)},
        ],
        "efecto_probabilidad": 0,
        "color": 0xFF0000,
    },
    "Infectado": {
        "emoji": "☢️",
        "hp": 150,
        "daño": (9, 10),
        "peso": 20,
        "lugares": ["Hospital", "Comisaría", "Refugio militar"],
        "loot_overos": (35, 50),
        "loot_item": None,
        "items": [
            {"item": "Chatarra", "chance": 80, "cantidad": (2, 4)},
            {"item": "Llave oxidada", "chance": 15, "cantidad": (1, 1)},
        ],
        "efecto_probabilidad": 0.3,
        "efecto": "Infectado",
        "color": 0xFF8C00,
    },
    "Lobo enfermo": {
        "emoji": "⚠️",
        "hp": 50,
        "daño": (4, 9),
        "peso": 70,
        "lugares": [
            "Metro",
            "Bosque",
            "Supermercado",
        ],
        "loot_overos": (10, 12),
        "loot_item": None,
        "items": [
            {"item": "Chatarra", "chance": 60, "cantidad": (1, 2)},
            {"item": "Cuero crudo", "chance": 50, "cantidad": (2, 4)},
            {"item": "Cuero", "chance": 10, "cantidad": (1, 2)},
        ],
        "efecto_probabilidad": 0.3,
        "efecto": "Sangrado",
        "color": 0xFFD000,
    },
    "Enfermero intóxicado": {
        "emoji": "⚠️",
        "hp": 80,
        "daño": (6, 10),
        "peso": 50,
        "lugares": [
            "Metro",
            "Hospital",
        ],
        "loot_overos": (40, 50),
        "loot_item": None,
        "items": [
            {"item": "Alcohol", "chance": 90, "cantidad": (1, 4)},
            {"item": "Alcohol antiséptico", "chance": 30, "cantidad": (2, 4)},
            {"item": "Venda estéril", "chance": 30, "cantidad": (1, 2)},
        ],
        "efecto_probabilidad": 0.3,
        "efecto": "Intoxicado",
        "color": 0xFFD000,
    },
    "Torreta AF-05": {
        "emoji": "☢️",
        "hp": 200,
        "daño": (15, 20),
        "peso": 1,
        "lugares": [
            "Refugio militar",
            "Banco",
        ],
        "loot_overos": (30, 40),
        "loot_item": None,
        "items": [
            {"item": "Munición 9mm", "chance": 30, "cantidad": (20, 25)},
            {"item": "Chatarra", "chance": 30, "cantidad": (5, 10)},
            {"item": "Aluminio", "chance": 20, "cantidad": (2, 3)},
        ],
        "efecto_probabilidad": 0.3,
        "efecto": "Herida grave",
        "color": 0xFF8C00,
    },
    "Aberración mal oliente": {
        "emoji": "☢️",
        "hp": 35,
        "daño": (10, 15),
        "peso": 20,
        "lugares": [
            "Refugio militar",
            "Bosque",
        ],
        "loot_overos": (30, 40),
        "loot_item": None,
        "items": [
            {"item": "Cuero crudo", "chance": 50, "cantidad": (1, 4)},
            {"item": "Pólvora", "chance": 30, "cantidad": (2, 3)},
            {"item": "Pilas", "chance": 10, "cantidad": (1, 2)},
        ],
        "efecto_probabilidad": 0.3,
        "efecto": "Intoxicado",
        "color": 0xFF8C00,
    },
    ###JEFES/MINI JEFES
    "Horror": {
        "emoji": "☣️",
        "hp": 500,
        "daño": (20, 30),
        "peso": 2,
        "lugares": ["Refugio militar"],
        "loot_overos": (300, 1000),
        "loot_item": None,
        "items": [
            {"item": "Pistola del Abismo", "chance": 50, "cantidad": (1, 1)},
            {"item": "Llave oxidada", "chance": 15, "cantidad": (1, 1)},
        ],
        "efecto_probabilidad": 0.3,
        "logro_derrota": "jefe_1",
        "efecto": "Infectado",
        "color": 0x2F4F4F,
    },
}
