# Eventos disponibles durante la exploración.

EVENTS = [
    {
        "mensaje": "🌫️ No encuentras nada interesante.",
        "overos": 0,
        "item": None,
        "effect": None,
        "chance": 40,
        "damage": 0,
    },
    {
        "mensaje": "🐺 Una criatura sale de entre las sombras y logra herirte antes de escapar.",
        "overos": 0,
        "item": None,
        "effect": "Herida grave",
        "chance": 10,
        "damage": 10,
    },
    {
        "mensaje": "🦴 Encuentras un pequeño montón de Overos oculto entre los escombros.",
        "overos": (5, 20),
        "item": None,
        "effect": None,
        "chance": 15,
        "damage": 0,
    },
    {
        "mensaje": "🏚️ Encuentras una casa abandonada.",
        "overos": 0,
        "item": "Venda",
        "effect": None,
        "chance": 30,
        "damage": 0,
    },
    {
        "mensaje": "🏚️ Registraste una casa abandonada. Todo estaba revuelto, pero aún quedaba algo útil.",
        "overos": (2, 8),
        "damage": 0,
        "effect": None,
        "item": "Venda",
        "chance": 5,
    },
    {
        "mensaje": "🛒 El supermercado estaba completamente saqueado.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 8,
    },
    {
        "mensaje": "🐀 Una rata salió disparada entre la basura y te hizo pegar un buen susto.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 7,
    },
    {
        "mensaje": "🦴 Encontraste unos Overos escondidos dentro de un zapato viejo.",
        "overos": (4, 10),
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 5,
    },
    {
        "mensaje": "🚪 Forzaste una puerta oxidada y terminaste cortándote.",
        "overos": 0,
        "damage": 6,
        "effect": "Rasguño",
        "item": None,
        "chance": 4,
    },
    {
        "mensaje": "🌧️ La lluvia limpió el aire. Hoy todo parece un poco más tranquilo.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 6,
    },
    {
        "mensaje": "🎒 Encontraste una mochila olvidada bajo unos escombros.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": "Botella de agua",
        "chance": 5,
    },
    {
        "mensaje": "👤 Viste a otro superviviente a la distancia. Ambos decidieron ignorarse.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 5,
    },
    {
        "mensaje": "💀 Un cadáver aún conservaba algunas pertenencias.",
        "overos": (6, 14),
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 4,
    },
    {
        "mensaje": "🐕 Un perro callejero comenzó a perseguirte. Lograste escapar.",
        "overos": 0,
        "damage": 3,
        "effect": None,
        "item": None,
        "chance": 5,
    },
    {
        "mensaje": "📦 Encontraste una caja militar vacía.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 6,
    },
    {
        "mensaje": "🧃 Una botella seguía sellada.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": "Botella de agua",
        "chance": 4,
    },
    {
        "mensaje": "🩹 Un pequeño botiquín seguía intacto.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": "Venda",
        "chance": 4,
    },
    {
        "mensaje": "🍖 Encontraste comida que todavía parecía comestible.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": "Comida enlatada",
        "chance": 5,
    },
    {
        "mensaje": "⚠️ Pisaste un clavo oxidado.",
        "overos": 0,
        "damage": 7,
        "effect": "Cortadura leve",
        "item": None,
        "chance": 4,
    },
    {
        "mensaje": "📚 Entraste en una biblioteca. Todo estaba cubierto de polvo.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 5,
    },
    {
        "mensaje": "🔦 Encontraste una linterna entre unos cajones.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": "Linterna",
        "chance": 2,
    },
    {
        "mensaje": "😐 Caminaste durante horas... no ocurrió absolutamente nada.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 10,
    },
    {
        "mensaje": "💰 Bajo una baldosa suelta encontraste algunos Overos.",
        "overos": (5, 12),
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 5,
    },
    {
        "mensaje": "🧪 Bebiste agua contaminada sin darte cuenta.",
        "overos": 0,
        "damage": 4,
        "effect": "Intoxicado",
        "item": None,
        "chance": 2,
    },
    {
        "mensaje": "🦅 Un cuervo te arrebató algo de las manos... aunque realmente no llevabas nada.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 6,
    },
    {
        "mensaje": "🚗 Registraste un automóvil abandonado.",
        "overos": (2, 6),
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 5,
    },
    {
        "mensaje": "📻 Una vieja radio seguía emitiendo estática.",
        "overos": 0,
        "damage": 0,
        "effect": None,
        "item": None,
        "chance": 5,
    },
    {
        "mensaje": "🩸 Te resbalaste entre los escombros y te golpeaste con fuerza.",
        "overos": 0,
        "damage": 10,
        "effect": "Sangrando",
        "item": None,
        "chance": 3,
    },
    {
        "mensaje": "🍀 Hoy la suerte estuvo de tu lado. Encontraste un pequeño escondite.",
        "overos": (10, 20),
        "damage": 0,
        "effect": None,
        "item": "Venda",
        "chance": 2,
    },
]
