ITEMS = {
    "Venda": {
        "descripcion": "Detiene hemorragias y cura heridas leves.",
        "descripcion_larga": "Un vendaje sencillo pero útil para detener sangrados y tratar heridas menores.",
        "tipo": "curacion",
        "categoria": "Medicina",
        "usable": True,
        "acumulable": True,
        "rareza": "comun",
        "valor": 10,
        "cura": ["Rasguño", "Sangrando", "Cortadura leve"],
        "vida": 0,
        "emoji": "🩹",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🩹 Limpias la herida y colocas una venda nueva. La herida ha sido tratada.",
        "encontrable": True,
    },
    "Antídoto": {
        "descripcion": "Neutraliza sustancias tóxicas.",
        "descripcion_larga": "Un compuesto médico capaz de contrarrestar diferentes tipos de intoxicaciones.",
        "tipo": "curacion",
        "categoria": "Medicina",
        "usable": True,
        "acumulable": True,
        "rareza": "raro",
        "valor": 60,
        "cura": ["Intoxicado"],
        "vida": 0,
        "emoji": "🧪",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🧪 Tomas el antídoto y el veneno comienza a abandonar tu cuerpo.",
        "encontrable": True,
    },
    "Comida enlatada": {
        "descripcion": "Recupera un poco de vida.",
        "descripcion_larga": "Una lata de comida conservada durante años. No es deliciosa, pero mantiene con vida.",
        "tipo": "consumible",
        "categoria": "Comida",
        "usable": True,
        "acumulable": True,
        "rareza": "comun",
        "valor": 15,
        "cura": [],
        "vida": 15,
        "emoji": "🥫",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🥫 Abres la lata y comes lo que queda. Recuperas fuerzas.",
        "encontrable": True,
    },
    "Botella de agua": {
        "descripcion": "Agua potable.",
        "descripcion_larga": "Una botella con agua limpia. Un recurso básico en cualquier situación de supervivencia.",
        "tipo": "consumible",
        "categoria": "Comida",
        "usable": True,
        "acumulable": True,
        "rareza": "comun",
        "valor": 8,
        "cura": [],
        "vida": 5,
        "emoji": "💧",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "💧 Tomas un poco de agua y recuperas algo de energía.",
        "encontrable": True,
    },
    "Linterna": {
        "descripcion": "Ilumina lugares oscuros.",
        "descripcion_larga": "Una linterna resistente que puede ayudarte a explorar zonas donde la luz no llega.",
        "tipo": "herramienta",
        "categoria": "Herramienta",
        "usable": True,
        "acumulable": False,
        "rareza": "poco_comun",
        "valor": 80,
        "cura": [],
        "vida": 0,
        "emoji": "🔦",
        "efecto_uso": "linterna",
        "duracion": None,
        "mensaje_uso": "🔦 Enciendes la linterna. Ahora puedes ver mejor en la oscuridad.",
        "encontrable": True,
    },
    "Llave oxidada": {
        "descripcion": "Quizá abra alguna puerta olvidada.",
        "descripcion_larga": "Una vieja llave cubierta de óxido. Nadie sabe qué puerta puede abrir.",
        "tipo": "especial",
        "categoria": "Especial",
        "usable": False,
        "acumulable": False,
        "rareza": "raro",
        "valor": 100,
        "cura": [],
        "vida": 0,
        "emoji": "🗝️",
        "efecto_uso": "llave",
        "duracion": None,
        "mensaje_uso": "",
        "encontrable": True,
    },
    "Botiquín": {
        "descripcion": "Un kit médico bastante completo.",
        "descripcion_larga": "Un botiquín de emergencia con varios suministros médicos capaces de tratar heridas más graves.",
        "tipo": "curacion",
        "categoria": "Medicina",
        "usable": True,
        "acumulable": True,
        "rareza": "epico",
        "valor": 120,
        "cura": ["Rasguño", "Cortadura leve", "Sangrando", "Herida grave"],
        "vida": 30,
        "emoji": "🏥",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🏥 Abres el botiquín y utilizas sus suministros médicos. Tus heridas mejoran.",
        "encontrable": True,
    },
    "Analgésicos": {
        "descripcion": "Reducen el dolor y ayudan a recuperarte.",
        "descripcion_larga": "Un paquete de medicamentos que reduce el dolor y permite continuar pese a las heridas.",
        "tipo": "medicina",
        "categoria": "Medicina",
        "usable": True,
        "acumulable": True,
        "rareza": "poco_comun",
        "valor": 45,
        "cura": [],
        "vida": 20,
        "emoji": "💊",
        "efecto_uso": "reducir_dolor",
        "duracion": 3,
        "mensaje_uso": "💊 Tomas los analgésicos y el dolor disminuye temporalmente.",
        "encontrable": True,
    },
    "Suero": {
        "descripcion": "Ayuda a combatir infecciones graves.",
        "descripcion_larga": "Un tratamiento médico avanzado utilizado para combatir infecciones peligrosas.",
        "tipo": "medicina",
        "categoria": "Medicina",
        "usable": True,
        "acumulable": True,
        "rareza": "epico",
        "valor": 150,
        "cura": ["Infectado"],
        "vida": 15,
        "emoji": "🧬",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🧬 Aplicas el suero y tu cuerpo comienza a combatir la infección.",
        "encontrable": True,
    },
    "Alcohol medicinal": {
        "descripcion": "Desinfecta heridas recientes.",
        "descripcion_larga": "Alcohol médico utilizado para limpiar heridas y evitar complicaciones.",
        "tipo": "curacion",
        "categoria": "Medicina",
        "usable": True,
        "acumulable": True,
        "rareza": "comun",
        "valor": 12,
        "cura": ["Rasguño"],
        "vida": 0,
        "emoji": "🧴",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🧴 Limpias la herida con alcohol y evitas que empeore.",
        "encontrable": True,
    },
    "Vendaje estéril": {
        "descripcion": "Un vendaje de mejor calidad.",
        "descripcion_larga": "Un vendaje médico preparado para tratar heridas más complicadas.",
        "tipo": "curacion",
        "categoria": "Medicina",
        "usable": True,
        "acumulable": True,
        "rareza": "poco_comun",
        "valor": 35,
        "cura": ["Cortadura leve", "Sangrando"],
        "vida": 10,
        "emoji": "🩺",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🩺 Colocas un vendaje estéril y la herida mejora notablemente.",
        "encontrable": True,
    },
    "Ración militar": {
        "descripcion": "Comida energética utilizada por soldados.",
        "descripcion_larga": "Una ración diseñada para mantener soldados activos durante largas operaciones.",
        "tipo": "consumible",
        "categoria": "Comida",
        "usable": True,
        "acumulable": True,
        "rareza": "raro",
        "valor": 70,
        "cura": [],
        "vida": 35,
        "emoji": "🎖️",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🎖️ Consumes la ración militar y recuperas una gran cantidad de energía.",
        "encontrable": True,
    },
    "Barra energética": {
        "descripcion": "Recupera algo de energía rápidamente.",
        "descripcion_larga": "Una barra nutritiva que proporciona energía rápida cuando más se necesita.",
        "tipo": "consumible",
        "categoria": "Comida",
        "usable": True,
        "acumulable": True,
        "rareza": "comun",
        "valor": 10,
        "cura": [],
        "vida": 10,
        "emoji": "🍫",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🍫 Comes la barra energética y recuperas algo de fuerza.",
        "encontrable": True,
    },
    "Bebida isotónica": {
        "descripcion": "Ayuda a hidratarte mejor que el agua.",
        "descripcion_larga": "Una bebida deportiva que repone líquidos y minerales perdidos.",
        "tipo": "consumible",
        "categoria": "Comida",
        "usable": True,
        "acumulable": True,
        "rareza": "poco_comun",
        "valor": 25,
        "cura": [],
        "vida": 12,
        "emoji": "🥤",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "🥤 Bebes la bebida isotónica y recuperas energía.",
        "encontrable": True,
    },
    "Café instantáneo": {
        "descripcion": "☕ Una bebida caliente que levanta el ánimo.",
        "descripcion_larga": "Un pequeño lujo encontrado entre los restos de una antigua tienda.",
        "tipo": "consumible",
        "categoria": "Comida",
        "usable": True,
        "acumulable": True,
        "rareza": "comun",
        "valor": 15,
        "cura": [],
        "vida": 8,
        "emoji": "☕",
        "efecto_uso": "energia",
        "duracion": 2,
        "mensaje_uso": "☕ Preparas el café y recuperas algo de ánimo.",
        "encontrable": True,
    },
    "Chocolate": {
        "descripcion": "Un pequeño lujo en medio del desastre.",
        "descripcion_larga": "Un chocolate viejo pero todavía comestible. Un pequeño recuerdo del mundo anterior.",
        "tipo": "consumible",
        "categoria": "Comida",
        "usable": True,
        "acumulable": True,
        "rareza": "comun",
        "valor": 12,
        "cura": [],
        "vida": 6,
        "emoji": "🍫",
        "efecto_uso": "moral",
        "duracion": 1,
        "mensaje_uso": "🍫 Comes el chocolate y por un momento olvidas el desastre.",
        "encontrable": True,
    },
    "Pilas": {
        "descripcion": "Sirven para alimentar dispositivos electrónicos.",
        "descripcion_larga": "Un paquete de pilas que todavía conserva algo de carga. Puede servir para reparar o activar equipos.",
        "tipo": "material",
        "categoria": "Material",
        "usable": False,
        "acumulable": True,
        "rareza": "comun",
        "valor": 8,
        "cura": [],
        "vida": 0,
        "emoji": "🔋",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "",
        "encontrable": True,
    },
    "Cuerda": {
        "descripcion": "Siempre puede resultar útil.",
        "descripcion_larga": "Una cuerda resistente que puede utilizarse para reparar, construir o superar obstáculos.",
        "tipo": "material",
        "categoria": "Material",
        "usable": False,
        "acumulable": True,
        "rareza": "comun",
        "valor": 15,
        "cura": [],
        "vida": 0,
        "emoji": "🪢",
        "efecto_uso": None,
        "duracion": None,
        "mensaje_uso": "",
        "encontrable": True,
    },
    "Navaja": {
        "descripcion": "Una pequeña herramienta multiusos.",
        "descripcion_larga": "Una navaja plegable que puede utilizarse para diferentes tareas durante la supervivencia.",
        "tipo": "herramienta",
        "categoria": "Herramienta",
        "usable": False,
        "acumulable": False,
        "rareza": "poco_comun",
        "valor": 50,
        "cura": [],
        "vida": 0,
        "emoji": "🔪",
        "efecto_uso": "herramienta_corte",
        "duracion": None,
        "mensaje_uso": "",
        "encontrable": True,
    },
    "Mapa viejo": {
        "descripcion": "Muestra parte de la ciudad antes del desastre.",
        "descripcion_larga": "Un mapa antiguo con zonas marcadas que podrían revelar lugares importantes.",
        "tipo": "especial",
        "categoria": "Especial",
        "usable": False,
        "acumulable": False,
        "rareza": "raro",
        "valor": 150,
        "cura": [],
        "vida": 0,
        "emoji": "🗺️",
        "efecto_uso": "mapa",
        "duracion": None,
        "mensaje_uso": "",
        "encontrable": True,
    },
    "Encendedor": {
        "descripcion": "Todavía funciona.",
        "descripcion_larga": "Un encendedor viejo que aún conserva combustible y puede generar fuego.",
        "tipo": "herramienta",
        "categoria": "Herramienta",
        "usable": False,
        "acumulable": False,
        "rareza": "comun",
        "valor": 20,
        "cura": [],
        "vida": 0,
        "emoji": "🔥",
        "efecto_uso": "fuego",
        "duracion": None,
        "mensaje_uso": "",
        "encontrable": True,
    },
}
